name: Auto tweet bot

on:
  schedule:
    - cron: '32 20 * * *'  
  workflow_dispatch:   

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Run fetch_playlist.py
        run: python fetch_playlist.py

      - name: Run playlist_to_csv.py
        run: python playlist_to_csv.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add playlist.json
          git commit -m "update playlist.csv"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}